### ISSUE TITLE
GenStateM cast does not use execution context of the appropriate process

### ISSUE THREAD

**Issue by artable** [yenrab/SwErl#8]
[here](https://github.com/yenrab/SwErl/blob/29b9f757fdb052fa07ca853ac05c9809df982d45/Sources/SwErl/GenStateM.swift#L250)

**Comment by yenrabbyui** [comment]
I'm not understanding this one. Explain please.

**Comment by artable** [comment]
all execution and especially state access should happen on the process's private serial queue. Indeed the apply through global().async does nothing to serialize the protected activity on the GenStateM.
Though I am not at my machine at the moment and therefore can't properly demonstrate, code correcting it would look something like this:
```swift
public static func cast(PID:Pid,message:SwErlMessage){
        //don't wait for a return
        //it doesn't matter which queue is used here. This is not the queue
        //on which the processing will happen


        //if the pid hasn't been registered correctly, return.
        guard let process = Registrar.getProcess(forID: PID) else{
            return
        }
        process.queue.async {
            guard let state = Registrar.getProcessState(forID: PID) else {
                return
            }
            guard let (_,handleCast,_,_) = process.GenStatemProcessWrappers else {
                return
            }
            //execute the handleCast function
            let (_,updatedState) = handleCast(message,state)
            Registrar.setProcessState(forID: PID, value: updatedState)
        }
    }
```

I do not believe that any use of the global dispatch queues is necessary here. The process calling this thing is sending a message, and in the architecture we have, I think it makes sense to allow the process of sending the message to take place in the local execution context. Every dispatch queue item does add overhead, so unless use of the global queues improves our fault boundaries or gives us good usage semantics, I recommend we skip it.

**Comment by yenrabbyui** [comment]
Here is the code for the Registrar.setProcessState/2 function. It is async and uses the registrar's underlying barrier. That should stop all additional changes and access until the change completes. I'm not seeing what your change would do.

`static func setProcessState(forID: Pid, value: Any) {
        return queue.async(flags: .barrier){ local.processStates[forID] = value }
    }`

**Comment by artable** [comment]
The registrar's queue protects the underlying dictionary against concurrent
reads and writes to prevent memory errors arising from concurrent actions
on the dictionary, but it does not serialize access to individual keys and
values. If every process does not have its own serial queue, then the
registrar's dictionary would allow for race conditions on the state values
of the processes. Notably, this error exists even with a completely
serialized dictionary queue.

The registrar's private concurrent queue only exists to solve the
concurrency issues intrinsic to Swift's default dictionary implementation.

**Comment by yenrabbyui** [comment]
So here is the code for the Registrar.getProcessState. It uses the same queue as the setProcessState function. Same queue. What would adding another queue on top of this one accomplish. Both reads and writes are using the same queue. Would it not be better to just add a barrier here?

`static func getProcessState(forID: Pid) -> Any? {
        return queue.sync{ local.processStates[forID] }
    }`

**Comment by yenrab** [comment]
resubmit using the appropriate template
